
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftmultiplierleftplusminusadjoint comma crossProduct determinant dotProduct float int inverse lCurlyBracket lHardBracket matrix minus multiplier plus rCurlyBracket rHardBracket transpose vectorexpression : termterm : factor\n            | vector\n            | comma\n            | float\n            | int\n            | matrix\n            | multiplierfactor : lCurlyBracket expression rCurlyBracket\n              | lHardBracket expression rHardBracketexpression : expression plus vectorexpression : expression minus vectorexpression : expression plus matrixexpression : expression minus matrixexpression : multiplier vectorexpression : multiplier matrixexpression : matrix matrixexpression : transpose matrixexpression : determinant matrixexpression : vector dotProduct vectorexpression : inverse matrixexpression : adjoint matrix'
    
_lr_action_items = {'multiplier':([0,14,15,],[5,5,5,]),'matrix':([0,4,5,6,7,8,9,14,15,16,17,],[4,19,21,22,23,24,25,4,4,29,31,]),'transpose':([0,14,15,],[6,6,6,]),'determinant':([0,14,15,],[7,7,7,]),'vector':([0,5,14,15,16,17,18,],[3,20,3,3,28,30,32,]),'inverse':([0,14,15,],[8,8,8,]),'adjoint':([0,14,15,],[9,9,9,]),'comma':([0,14,15,],[11,11,11,]),'float':([0,14,15,],[12,12,12,]),'int':([0,14,15,],[13,13,13,]),'lCurlyBracket':([0,14,15,],[14,14,14,]),'lHardBracket':([0,14,15,],[15,15,15,]),'$end':([1,2,3,4,5,10,11,12,13,19,20,21,22,23,24,25,28,29,30,31,32,33,34,],[0,-1,-3,-7,-8,-2,-4,-5,-6,-17,-15,-16,-18,-19,-21,-22,-11,-13,-12,-14,-20,-9,-10,]),'plus':([1,2,3,4,5,10,11,12,13,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,],[16,-1,-3,-7,-8,-2,-4,-5,-6,-17,-15,-16,-18,-19,-21,-22,16,16,-11,-13,-12,-14,-20,-9,-10,]),'minus':([1,2,3,4,5,10,11,12,13,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,],[17,-1,-3,-7,-8,-2,-4,-5,-6,-17,-15,-16,-18,-19,-21,-22,17,17,-11,-13,-12,-14,-20,-9,-10,]),'rCurlyBracket':([2,3,4,5,10,11,12,13,19,20,21,22,23,24,25,26,28,29,30,31,32,33,34,],[-1,-3,-7,-8,-2,-4,-5,-6,-17,-15,-16,-18,-19,-21,-22,33,-11,-13,-12,-14,-20,-9,-10,]),'rHardBracket':([2,3,4,5,10,11,12,13,19,20,21,22,23,24,25,27,28,29,30,31,32,33,34,],[-1,-3,-7,-8,-2,-4,-5,-6,-17,-15,-16,-18,-19,-21,-22,34,-11,-13,-12,-14,-20,-9,-10,]),'dotProduct':([3,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,14,15,],[1,26,27,]),'term':([0,14,15,],[2,2,2,]),'factor':([0,14,15,],[10,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term','expression',1,'p_expression_term','yacc_test.py',16),
  ('term -> factor','term',1,'p_term_vector','yacc_test.py',26),
  ('term -> vector','term',1,'p_term_vector','yacc_test.py',27),
  ('term -> comma','term',1,'p_term_vector','yacc_test.py',28),
  ('term -> float','term',1,'p_term_vector','yacc_test.py',29),
  ('term -> int','term',1,'p_term_vector','yacc_test.py',30),
  ('term -> matrix','term',1,'p_term_vector','yacc_test.py',31),
  ('term -> multiplier','term',1,'p_term_vector','yacc_test.py',32),
  ('factor -> lCurlyBracket expression rCurlyBracket','factor',3,'p_factor','yacc_test.py',36),
  ('factor -> lHardBracket expression rHardBracket','factor',3,'p_factor','yacc_test.py',37),
  ('expression -> expression plus vector','expression',3,'p_expression_plus_vector','yacc_test.py',42),
  ('expression -> expression minus vector','expression',3,'p_expression_minus_vector','yacc_test.py',51),
  ('expression -> expression plus matrix','expression',3,'p_expression_plus_matrix','yacc_test.py',60),
  ('expression -> expression minus matrix','expression',3,'p_expression_minus_matrix','yacc_test.py',66),
  ('expression -> multiplier vector','expression',2,'p_expression_scalar_vector','yacc_test.py',72),
  ('expression -> multiplier matrix','expression',2,'p_expression_scalar_matrix','yacc_test.py',78),
  ('expression -> matrix matrix','expression',2,'p_expression_cross_product_matrix','yacc_test.py',84),
  ('expression -> transpose matrix','expression',2,'p_expression_transpose_matrix','yacc_test.py',90),
  ('expression -> determinant matrix','expression',2,'p_expression_det_matrix','yacc_test.py',94),
  ('expression -> vector dotProduct vector','expression',3,'p_expression_dot_product_vector','yacc_test.py',98),
  ('expression -> inverse matrix','expression',2,'p_expression_inverse_matrix','yacc_test.py',102),
  ('expression -> adjoint matrix','expression',2,'p_expression_adjoint_matrix','yacc_test.py',106),
]
